{
    "name": "Ethiopian Hospital ERP",
    "summary": "Compliance-first hospital management foundation for Odoo 18 Community",
    "version": "18.0.1.5.0",
    "category": "Healthcare",
    "author": "Ethiopian Hospital ERP",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [
        "security/hospital_security.xml",
        "security/ir.model.access.csv",
        "data/hospital_sequence.xml",
        "views/department_views.xml",
        "views/doctor_views.xml",
        "views/medical_alert_views.xml",
        "views/disease_views.xml",
        "views/patient_tag_views.xml",
        "views/patient_family_views.xml",
        "views/patient_document_views.xml",
        "views/patient_views.xml",
        "views/pain_level_guide_views.xml",
        "views/patient_evaluation_views.xml",
        "views/patient_diagnosis_views.xml",
        "views/prescription_views.xml",
        "views/treatment_plan_views.xml",
        "views/laboratory_request_views.xml",
        "views/laboratory_result_views.xml",
        "views/appointment_views.xml",
        "views/encounter_views.xml",
        "views/consent_views.xml",
        "views/audit_log_views.xml",
        "reports/hospital_report_common.xml",
        "reports/patient_profile_template.xml",
        "reports/patient_report.xml",
        "reports/prescription_template.xml",
        "reports/prescription_report.xml",
        "reports/treatment_plan_template.xml",
        "reports/treatment_plan_report.xml",
        "reports/laboratory_request_template.xml",
        "reports/laboratory_request_report.xml",
        "reports/laboratory_result_template.xml",
        "reports/laboratory_result_report.xml",
        "views/hospital_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hospital_management/static/src/scss/hospital_theme.scss",
        ],
    },
    "application": True,
    "installable": True,
}
