{
    "name": "Hospital Billing",
    "summary": "Patient billing foundation for Ethiopian Hospital ERP",
    "version": "18.0.1.5.0",
    "category": "Healthcare",
    "author": "Synergy Tech soln",
    "license": "LGPL-3",
    "depends": ["hospital_management", "hospital_pharmacy", "hospital_radiology", "uom"],
    "data": [
        "security/hospital_billing_groups.xml",
        "security/ir.model.access.csv",
        "data/billing_sequence.xml",
        "views/billing_service_views.xml",
        "views/billing_account_views.xml",
        "views/charge_line_views.xml",
        "views/charge_receipt_views.xml",
        "views/appointment_billing_views.xml",
        "views/laboratory_billing_views.xml",
        "views/radiology_billing_views.xml",
        "views/pharmacy_billing_views.xml",
        "views/patient_bill_views.xml",
        "views/patient_bill_payment_wizard_views.xml",
        "views/patient_billing_views.xml",
        "views/billing_menus.xml",
        "reports/patient_bill_template.xml",
        "reports/patient_bill_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hospital_billing/static/src/scss/billing_theme.scss",
        ],
    },
    "application": True,
    "installable": True,
}
