{
    "name": "Hospital Inventory",
    "summary": "Hospital inventory and medical consumables control foundation",
    "version": "18.0.1.1.0",
    "category": "Healthcare",
    "author": "Synergy Tech solns",
    "license": "LGPL-3",
    "depends": [
        "hospital_management",
        "hospital_pharmacy",
        "hospital_procedure",
        "hospital_nursing",
        "hospital_radiology",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/inventory_sequence.xml",
        "data/inventory_location_data.xml",
        "data/inventory_category_data.xml",
        "views/inventory_location_views.xml",
        "views/inventory_category_views.xml",
        "views/opening_stock_views.xml",
        "views/inventory_item_views.xml",
        "views/inventory_batch_views.xml",
        "views/department_stock_views.xml",
        "views/stock_request_views.xml",
        "views/stock_movement_views.xml",
        "views/stock_consumption_views.xml",
        "views/patient_inventory_views.xml",
        "views/pharmacy_inventory_views.xml",
        "views/procedure_inventory_views.xml",
        "views/nursing_inventory_views.xml",
        "views/lab_inventory_views.xml",
        "views/radiology_inventory_views.xml",
        "views/inventory_menus.xml",
        "views/provenance_archive_views.xml",
        "reports/inventory_template.xml",
        "reports/inventory_report.xml",
        "reports/consumption_template.xml",
        "reports/consumption_report.xml",
        "reports/opening_stock_template.xml",
        "reports/opening_stock_report.xml",
    ],
    "demo": [
        "demo/inventory_demo_data.xml",
    ],
    "application": True,
    "installable": True,
}
