from . import test_cashier_desk_api
from . import test_insurance_credit_api
from . import test_cashier_payment_api
from . import test_front_desk_session_roles
from . import test_front_desk_payer_api
from . import test_front_desk_triage_api
from . import test_front_desk_worklist
from . import test_doctor_desk_api
from . import test_doctor_consultation_api
